services:
  minio:
    image: quay.io/minio/minio
    container_name: storage-sql-report
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: /bin/sh
    command: /usr/bin/setup-minio.sh
    restart: always
    volumes:
      - minio-data:/data
      - ./setup-minio.sh:/usr/bin/setup-minio.sh
      - ./lifecycle.json:/etc/minio/lifecycle.json

volumes:
  minio-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/sql-report/storage
      o: bind
