services:
  minio:
    image: quay.io/minio/minio
    container_name: storage-sql-report
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - minio-data:/data

volumes:
  minio-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/sql-report/storage
      o: bind
